In [10]:
import tensorflow as tf
import numpy as np
X = np.array([[73., 80., 75.],[93., 88., 93.],[89., 91., 90.],
          [96., 98., 100.],[73., 66., 70.]], dtype = np.float32)
Y = np.array([[152.],[185.],[180.],[196.],[142.]], dtype = np.float32)

#X = x_data[:, :]
#Y = y_data[:, :]

# W는 3*1 행렬
W = tf.Variable(tf.random.normal([3,1]))
# b는 1*1 헹렬
b = tf.Variable(tf.random.normal([1]))

#XW+b 행렬의 곱으로 표현
def multiLinear(x):
    return tf.matmul(X, W) + b

optimizer = tf.optimizers.SGD(learning_rate = 1e-5)

for step in range(2001):
    with tf.GradientTape() as g:
        hypothesis = multiLinear(X)
        cost = tf.reduce_mean(tf.square(hypothesis-Y))
    gradients = g.gradient(cost, [W, b])
    #업데이트
    optimizer.apply_gradients(zip(gradients, [W,b]))
    if step % 10 == 0:
        print("%i cost: %f \nprediction\n"% (step, cost), hypothesis.numpy())  



0 cost: 2142.445801 
prediction
 [[193.32079]
 [233.79185]
 [230.10014]
 [245.80205]
 [182.42163]]
10 cost: 4.055810 
prediction
 [[152.4155 ]
 [184.62299]
 [181.65509]
 [193.04733]
 [144.91663]]
20 cost: 4.032587 
prediction
 [[152.29366]
 [184.47282]
 [181.50902]
 [192.88896]
 [144.80055]]
30 cost: 4.028955 
prediction
 [[152.29523]
 [184.47096]
 [181.50905]
 [192.88972]
 [144.79762]]
40 cost: 4.025321 
prediction
 [[152.29715]
 [184.46951]
 [181.50949]
 [192.89093]
 [144.795  ]]
50 cost: 4.021738 
prediction
 [[152.29907]
 [184.46814]
 [181.50998]
 [192.89215]
 [144.79242]]
60 cost: 4.018100 
prediction
 [[152.301  ]
 [184.46674]
 [181.51045]
 [192.89342]
 [144.78984]]
70 cost: 4.014528 
prediction
 [[152.30287]
 [184.46535]
 [181.51091]
 [192.8946 ]
 [144.78725]]
80 cost: 4.010939 
prediction
 [[152.30476]
 [184.46393]
 [181.51138]
 [192.89584]
 [144.78467]]
90 cost: 4.007384 
prediction
 [[152.30667]
 [184.46259]
 [181.5119 ]
 [192.8971 ]
 [144.78212]]
100 cost: 4.003820 
predicti